### ISSUE TITLE
Key path and security groups

### ISSUE THREAD

**Issue by willmclaren** [hms-dbmi/hail-on-AWS-spot-instances#1]
Hi guys, great resource and thanks for sharing.

A couple of points that I came across while using the tool that could be clearer in the docs:

* the `PATH_TO_KEY` variable is the *directory* containing the key file, not the full path to the key file itself

* the security group set as `MASTER_SECURITY_GROUP` must have SSH access (port 22) from the machine running the script otherwise the script fails to log in to the master to execute the post-EMR installation

* I found installing awscli as instructed in the root environment on my Mac clashed with my existing python2 awscli setup. To avoid this I installed python3 using brew as instructed, then used a virtualenv to install the subsequent libraries and tools:

```
virtualenv -p python3 hail-spot
cd hail-spot/
source bin/activate
pip3 install --upgrade pip
pip3 install boto3 pandas botocore paramiko pyyaml nose tornado
pip3 install awscli
git clone https://github.com/hms-dbmi/hail-on-AWS-spot-instances
...etc...
```

**Comment by biocdeniz** [comment]
Hi @willmclaren,

* Correct, `PATH_TO_KEY` is the path to the directory. I added a note in the `.yaml` file to avoid ambiguity.

* Yes, the `MASTER_SECURITY_GROUP` needs to have port 22 open. That's why I added reference to this link: https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-security-groups.html but it doesn't hurt to explicitly say that
 
* Exactly, as stated at the beginning of the **Software requirements** section you need `Python3`  but if you use `pip3` you shouldn't expect any issues but definitely the best way to avoid clashing between versions is to use a virtualenv for one or the other.

Thank you for the feedback and the comments. I'm closing this thread. BTW I just got a notification about open issues just yesterday.
